/**
 * Created by hien.phanthe on 3/15/17.
 */
export const CONTACT_LOAD_SUCCEEDED = 'CONTACT/LOAD/SUCCEEDED';
export const CONTACT_LOAD_FAILED = 'CONTACT/LOAD/FAILED';
export const CONTACT_ADD_CALL = 'CONTACT/ADD/CALL';
export const CONTACT_ADDED_SUCCEEDED = 'CONTACT/ADDED/SUCCEEDED';
export const CONTACT_ADDED_FAILED = 'CONTACT/ADDED/FAILED';

